workflows:
  default-workflow:
    name: Docker Workflow
    scripts:
      - name: Pull Docker Image
        script: |
          docker pull alexrodri7/codemagic-local:latest

      - name: Build Project
        script: |
          docker run --rm alexrodri7/codemagic-local:latest mvn clean package

      - name: Run Tests
        script: |
          docker run --rm alexrodri7/codemagic-local:latest mvn test

    artifacts:
      - target/*.jar  # Artefactos generados que quieras guardar
