workflows:
  default-workflow:
    name: Docker Workflow
    scripts:
      # Paso 1: Ejecutar el contenedor Docker y compilar el proyecto
      - name: Build
        script: |
          docker pull alexrodri7/codemagic-local:latest
          docker run --rm alexrodri7/codemagic-local:latest mvn -B -DskipTests clean package
      
      # Paso 2: Ejecutar las pruebas en el contenedor Docker
      - name: Test
        script: |
          docker run --rm alexrodri7/codemagic-local:latest mvn test
    artifacts:
      - target/*.jar  # Especificar artefactos generados
