workflows:
  default-workflow:
    name: Docker Workflow
    scripts:
      - name: Pull Docker Image
        script: |
          docker pull alexrodri7/codemagic-local:latest  # Descargar la imagen desde Docker Hub

      - name: Build Project
        script: |
          docker run --rm alexrodri7/codemagic-local:latest mvn clean package  # Construir el proyecto

      - name: Run Tests
        script: |
          docker run --rm alexrodri7/codemagic-local:latest mvn test  # Ejecutar pruebas

    artifacts:
      - target/*.jar  # Guardar los artefactos generados
