workflows:
  default-workflow:
    name: Docker Workflow
    environment:
      image: "ubuntu:20.04"  # Entorno Linux compatible con Docker

    scripts:
      - name: Install Docker
        script: |
          apt-get update && apt-get install -y docker.io

      - name: Pull Docker Image
        script: |
          docker pull alexrodri7/codemagic-local:latest

      - name: Build Project
        script: |
          docker run --rm alexrodri7/codemagic-local:latest mvn clean package

      - name: Run Tests
        script: |
          docker run --rm alexrodri7/codemagic-local:latest mvn test

    artifacts:
      - target/*.jar
