workflows:
  default-workflow:
    name: Docker Workflow
    docker:
      image: "alexrodri7/codemagic-local:latest"  # Imagen Docker personalizada
    scripts:
      - name: Build Project
        script: mvn clean package
      - name: Run Tests
        script: mvn test
    artifacts:
      - target/*.jar  # Artefactos generados que quieras guardar
